### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by krishy2** [bphillips09/Control4-HA-Lock#1]
Hello,

I'd like to get information about your driver. Please let me know any contact of you.

Thanks

**Comment by bphillips09** [comment]
> Hello,
> 
> I'd like to get information about your driver. Please let me know any contact of you.
> 
> Thanks

Hi, I will respond here or on Discord: https://discord.com/invite/control4

To use this Home Assistant Lock entity driver, you just need this driver and the [Coordinator](https://github.com/bphillips09/Control4-HA-Coordinator) driver.
